FROM node:alpine3.18 as nodebuild
WORKDIR /frontend
COPY package*.json ./
RUN npm ci
COPY ./ ./
RUN npm run build

FROM nginx:1.23.3-alpine
WORKDIR /usr/share/nginx/htm
RUN rm -rf ./*
COPY --from=nodebuild /frontend/build .
ENTRYPOINT [ "nginx","-g","daemon off;" ]